### ISSUE TITLE
Language Workgroup webpage on swift.org leads to 403 restriction

### ISSUE THREAD

**Issue by Farial-mahmod** [apple/swift-org-website#359] opened 2023-08-17 19:39 UTC
Description:
Language Work Group on https://www.swift.org/blog/server-api-workgroup/ leads to a status 403 restriction. I tried multiple times but was restricted. I am interested to see if I can contribute to the language work group.

Tested On:
1. Safari 16.5 on MacOS Ventura
2. Firefox 116.2 on Windows 10

1. Go to https://www.swift.org/blog/server-api-workgroup/
2. See the issue of 403 restriction

Both the screenshots has been attached for better understanding below:

![swift-org-workgroup-403](https://github.com/apple/swift-org-website/assets/60639522/d903c5b4-c943-4a8e-ac8d-038473f98193)

![swift-org-403](https://github.com/apple/swift-org-website/assets/60639522/241e4b2a-e3e7-4e90-8666-275870e72865)

**Comment by alexandersandberg** [comment] 2023-08-18 06:46
Thanks for reporting this. Is this a duplicate of #358? You mention "language workgroup" but the erroring link seems to be the same here as in the other issue (https://www.swift.org/server-apis/).

**Comment by alexandersandberg** [comment] 2023-09-13 10:36
Closing this as a duplicate of #358.

**Closed by alexandersandberg** 2023-09-13 10:36 UTC
Labels: bug
